service: nest-mr

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-dynamodb-local
  - serverless-offline

functions:
 app:
   handler: dist/main.handler
   events:
     - http:
         method: any
         path: /{proxy+}
         cors: true
     - http:
         method: any
         path: /
         cors: true

package:
  exclude:
    - README.md
    - .dynamodb/**

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  deploymentMethod: direct
  
  iam:
    role: 
      statements: ${file(iam/usersTableIAM.yml)}

custom: 
    esbuild: 
      bundle: true
      minify: false
      sourcemap: true
      exclude: 
        - aws-sdk
      target: node18
      define: 'require.resolve: undefined'
      platform: node
      concurrency: 10
    
    # dynamodb: 
    #   start: 
    #     port: 5000
    #     inMemory: true
    #     migrate: true
      
    #   stages: 
    #     - dev

    # usersTable:
    #   name: UsersTable
    #   arn: !GetAtt usersTable.Arn

# resources: 
#     Resources: 
#       usersTable: ${file(resources/usersTable.yml):usersTable}
     